In [95]:
import random
import math


def roll_dice(random, number_of_rolls= 6, sides_on_die=6, start_at=0):
    '''
        Simulate a normal distribution of values through a dice simulator
    '''
    total = 0
    for i in range(number_of_rolls):
        total += random.randint(start_at,sides_on_die-1+start_at)
    return total

def gen_dice(max_buckets, widest_normal_dist=True):
    '''
        Input the number of buckets and the whether you want a wide or narrow distribution and you 
        will get back the required arguments to roll dice
    '''
    n = max_buckets - 1
    if widest_normal_dist==True:
        for i in range(int(math.sqrt(n)),1,-1):
            if n%i == 0:
                break        
    else:
        for i in range(2,n+1):
            if n%i == 0:
                break

    rolls = n//i
    sides = i+1
    return rolls, sides

def rand_normal_dist(random, n, widest_normal_dist=True):
    '''
        Get a random number between 0 and n, using a standard normal disribution.
        widest_normal_dist=True will use the widest distribuion possible (larger std)
    '''
    rolls,sides = gen_dice(n,widest_normal_dist);
    return roll_dice(random,rolls, sides,0)



def ssh_gen(count):
    '''
    Generate count number of unique social-security numbers
    '''    
    prefix = list(range(1000))
    middle = list(range(100))
    suffix = list(range(10000))
    numbers = []
    random.shuffle(prefix)
    random.shuffle(middle)
    random.shuffle(suffix)    
    for i in range(count):
        p = random.choice(prefix)
        m = random.choice(middle)
        s = suffix.pop()
        number = f"{p:03}-{m:02}-{s:04}"
        numbers.append(number)
    return numbers

In [54]:
import json
ssn = ssh_gen(235)
with open ('seeddata/funny-person.json') as f:
    people = json.load(f)
    
for i in range(len(people)):
    people[i]['ssn'] = ssn[i]
    people[i]['_key'] = ssn[i]

people

[{'_key': '515-62-5368',
  'email': 'akuss@armyspy.com',
  'first_name': 'Abby',
  'last_name': 'Kuss',
  'ssn': '515-62-5368'},
 {'_key': '781-00-9353',
  'email': 'aantium87@dayrep.com',
  'first_name': 'Adam',
  'last_name': 'Antium',
  'ssn': '781-00-9353'},
 {'_key': '559-55-4706',
  'email': 'aowse@dayrep.com',
  'first_name': 'Addie',
  'last_name': 'Owse',
  'ssn': '559-55-4706'},
 {'_key': '533-92-2796',
  'email': 'asomewun17@einrot.com',
  'first_name': 'Aiden',
  'last_name': 'Somewun',
  'ssn': '533-92-2796'},
 {'_key': '369-37-9012',
  'email': 'aknowone28@gustr.com',
  'first_name': 'Aiden',
  'last_name': 'Knowone',
  'ssn': '369-37-9012'},
 {'_key': '056-62-8945',
  'email': 'afrecso@dayrep.com',
  'first_name': 'Al',
  'last_name': 'Frecso',
  'ssn': '056-62-8945'},
 {'_key': '573-00-7626',
  'email': 'akohol@rhyta.com',
  'first_name': 'Al',
  'last_name': 'Kohol',
  'ssn': '573-00-7626'},
 {'_key': '603-25-3416',
  'email': 'allan.wrench@dayrep.com',
  'first_name': 'Allan',
  'last_name': 'Wrench',
  'ssn': '603-25-3416'},
 {'_key': '140-63-5030',
  'email': 'agator@dayrep.com',
  'first_name': 'Ally',
  'last_name': 'Gator',
  'ssn': '140-63-5030'},
 {'_key': '777-43-2728',
  'email': 'alma.frienzergon@dayrep.com',
  'first_name': 'Alma',
  'last_name': 'Frienzergon',
  'ssn': '777-43-2728'},
 {'_key': '253-27-5673',
  'email': 'amanda.hugginkiss@armyspy.com',
  'first_name': 'Amanda',
  'last_name': 'Hugginkiss',
  'ssn': '253-27-5673'},
 {'_key': '958-76-7513',
  'email': 'awavesofgrain@dayrep.com',
  'first_name': 'Amber',
  'last_name': 'Wavesofgrain',
  'ssn': '958-76-7513'},
 {'_key': '539-80-4459',
  'email': 'ajob@armyspy.com',
  'first_name': 'Anita',
  'last_name': 'Job',
  'ssn': '539-80-4459'},
 {'_key': '415-79-2532',
  'email': 'afavor55@armyspy.com',
  'first_name': 'Anita',
  'last_name': 'Favor',
  'ssn': '415-79-2532'},
 {'_key': '697-65-0170',
  'email': 'anita.shower@superrito.com',
  'first_name': 'Anita',
  'last_name': 'Shower',
  'ssn': '697-65-0170'},
 {'_key': '778-63-2969',
  'email': 'anita.sandwich@einrot.com',
  'first_name': 'Anita',
  'last_name': 'Sandwich',
  'ssn': '778-63-2969'},
 {'_key': '449-29-8961',
  'email': 'adewey@rhyta.com',
  'first_name': 'Anne',
  'last_name': 'Dewey',
  'ssn': '449-29-8961'},
 {'_key': '685-84-9242',
  'email': 'afirst99@dayrep.com',
  'first_name': 'April',
  'last_name': 'First',
  'ssn': '685-84-9242'},
 {'_key': '923-48-2864',
  'email': 'arial.photo@dayrep.com',
  'first_name': 'Arial',
  'last_name': 'Photo',
  'ssn': '923-48-2864'},
 {'_key': '121-56-1399',
  'email': 'asurvellence@einrot.com',
  'first_name': 'Arial',
  'last_name': 'Survellence',
  'ssn': '121-56-1399'},
 {'_key': '520-62-3750',
  'email': 'achoke@superrito.com',
  'first_name': 'Artie',
  'last_name': 'Choke',
  'ssn': '520-62-3750'},
 {'_key': '964-09-8650',
  'email': 'aborealis93@superrito.com',
  'first_name': 'Aurora',
  'last_name': 'Borealis',
  'ssn': '964-09-8650'},
 {'_key': '904-96-6707',
  'email': 'bdwyer76@rhyta.com',
  'first_name': 'Barb',
  'last_name': 'Dwyer',
  'ssn': '904-96-6707'},
 {'_key': '881-48-2053',
  'email': 'bbarion@armyspy.com',
  'first_name': 'Barb',
  'last_name': 'Barion',
  'ssn': '881-48-2053'},
 {'_key': '885-65-8247',
  'email': 'bdehatchett52@gustr.com',
  'first_name': 'Barry',
  'last_name': 'DeHatchett',
  'ssn': '885-65-8247'},
 {'_key': '002-69-6266',
  'email': 'bmii@superrito.com',
  'first_name': 'Barry',
  'last_name': 'Mii',
  'ssn': '002-69-6266'},
 {'_key': '607-57-5684',
  'email': 'bleif@gustr.com',
  'first_name': 'Basil',
  'last_name': 'Leif',
  'ssn': '607-57-5684'},
 {'_key': '581-41-4823',
  'email': 'balott@einrot.com',
  'first_name': 'Bette',
  'last_name': 'Alott',
  'ssn': '581-41-4823'},
 {'_key': '450-24-3116',
  'email': 'bette.itall@superrito.com',
  'first_name': 'Bette',
  'last_name': 'Itall',
  'ssn': '450-24-3116'},
 {'_key': '942-65-3816',
  'email': 'bmelator@superrito.com',
  'first_name': 'Bill',
  'last_name': 'Melator',
  'ssn': '942-65-3816'},
 {'_key': '738-93-9070',
  'email': 'bislate@dayrep.com',
  'first_name': 'Bill',
  'last_name': 'Islate',
  'ssn': '738-93-9070'},
 {'_key': '071-66-9248',
  'email': 'bdalmonds@superrito.com',
  'first_name': 'Blanche',
  'last_name': 'Dalmonds',
  'ssn': '071-66-9248'},
 {'_key': '265-16-2070',
  'email': 'benarreau@superrito.com',
  'first_name': 'Bo',
  'last_name': 'Enarreau',
  'ssn': '265-16-2070'},
 {'_key': '189-32-2043',
  'email': 'benweave73@superrito.com',
  'first_name': 'Bob',
  'last_name': 'Enweave',
  'ssn': '189-32-2043'},
 {'_key': '644-44-2632',
  'email': 'byourhair@dayrep.com',
  'first_name': 'Brayden',
  'last_name': 'Yourhair',
  'ssn': '644-44-2632'},
 {'_key': '998-42-5975',
  'email': 'bhair@armyspy.com',
  'first_name': 'Brayden',
  'last_name': 'Hair',
  'ssn': '998-42-5975'},
 {'_key': '199-26-3631',
  'email': 'bnaked69@superrito.com',
  'first_name': 'Buck',
  'last_name': 'Naked',
  'ssn': '199-26-3631'},
 {'_key': '426-10-1853',
  'email': 'buck.annaquarter@superrito.com',
  'first_name': 'Buck',
  'last_name': 'Annaquarter',
  'ssn': '426-10-1853'},
 {'_key': '324-26-5765',
  'email': 'ccorder@gustr.com',
  'first_name': 'Cam',
  'last_name': 'Corder',
  'ssn': '324-26-5765'},
 {'_key': '423-81-0912',
  'email': 'cpayne54@dayrep.com',
  'first_name': 'Cam',
  'last_name': 'Payne',
  'ssn': '423-81-0912'},
 {'_key': '403-23-1996',
  'email': 'crha@superrito.com',
  'first_name': 'Cam',
  'last_name': 'Rha',
  'ssn': '403-23-1996'},
 {'_key': '591-22-7643',
  'email': 'cdryve50@gustr.com',
  'first_name': 'Carmen',
  'last_name': 'Dryve',
  'ssn': '591-22-7643'},
 {'_key': '989-69-3061',
  'email': 'ckane36@dayrep.com',
  'first_name': 'Candi',
  'last_name': 'Kane',
  'ssn': '989-69-3061'},
 {'_key': '990-75-8528',
  'email': 'candi.dish@dayrep.com',
  'first_name': 'Candi',
  'last_name': 'Dish',
  'ssn': '990-75-8528'},
 {'_key': '489-42-0677',
  'email': 'cling@dayrep.com',
  'first_name': 'Carol',
  'last_name': 'Ling',
  'ssn': '489-42-0677'},
 {'_key': '721-62-7502',
  'email': 'cdababbi@einrot.com',
  'first_name': 'Carrie',
  'last_name': 'Dababbi',
  'ssn': '721-62-7502'},
 {'_key': '271-17-9979',
  'email': 'cmeehom72@dayrep.com',
  'first_name': 'Carrie',
  'last_name': 'Meehom',
  'ssn': '271-17-9979'},
 {'_key': '268-56-6876',
  'email': 'csalad@armyspy.com',
  'first_name': 'Cesar',
  'last_name': 'Salad',
  'ssn': '268-56-6876'},
 {'_key': '138-77-4994',
  'email': 'chase.lounge@gustr.com',
  'first_name': 'Chase',
  'last_name': 'Lounge',
  'ssn': '138-77-4994'},
 {'_key': '922-57-4632',
  'email': 'cpeanugget@gustr.com',
  'first_name': 'Chris',
  'last_name': 'Peanugget',
  'ssn': '922-57-4632'},
 {'_key': '168-37-3649',
  'email': 'chuck.itupp@superrito.com',
  'first_name': 'Chuck',
  'last_name': 'Itupp',
  'ssn': '168-37-3649'},
 {'_key': '552-84-4562',
  'email': 'cpotts@gustr.com',
  'first_name': 'Clay',
  'last_name': 'Potts',
  'ssn': '552-84-4562'},
 {'_key': '565-48-1437',
  'email': 'clifton.owhere@rhyta.com',
  'first_name': 'Clifton',
  'last_name': 'Owhere',
  'ssn': '565-48-1437'},
 {'_key': '122-60-4857',
  'email': 'cole.deggs@rhyta.com',
  'first_name': 'Cole',
  'last_name': 'Deggs',
  'ssn': '122-60-4857'},
 {'_key': '111-56-7793',
  'email': 'cook.myefoud@superrito.com',
  'first_name': 'Cook',
  'last_name': 'Myefoud',
  'ssn': '111-56-7793'},
 {'_key': '459-74-4608',
  'email': 'cchocolate@superrito.com',
  'first_name': 'Craven',
  'last_name': 'Chocolate',
  'ssn': '459-74-4608'},
 {'_key': '192-66-1366',
  'email': 'ccleer@superrito.com',
  'first_name': 'Crystal',
  'last_name': 'Cleer',
  'ssn': '192-66-1366'},
 {'_key': '373-57-9678',
  'email': 'crystal.ball@superrito.com',
  'first_name': 'Crystal',
  'last_name': 'Ball',
  'ssn': '373-57-9678'},
 {'_key': '319-99-8418',
  'email': 'dean.ofstudents@einrot.com',
  'first_name': 'Dean',
  'last_name': 'Ofstudents',
  'ssn': '319-99-8418'},
 {'_key': '716-44-7134',
  'email': 'ddelyons@rhyta.com',
  'first_name': 'Dan',
  'last_name': 'Delyons',
  'ssn': '716-44-7134'},
 {'_key': '645-07-9505',
  'email': 'dinator@superrito.com',
  'first_name': 'Dom',
  'last_name': 'Inator',
  'ssn': '645-07-9505'},
 {'_key': '321-52-1883',
  'email': 'dclosed79@superrito.com',
  'first_name': 'Doris',
  'last_name': 'Closed',
  'ssn': '321-52-1883'},
 {'_key': '736-73-6252',
  'email': 'dnolongeropen76@dayrep.com',
  'first_name': 'Doris',
  'last_name': 'Nolongeropen',
  'ssn': '736-73-6252'},
 {'_key': '531-22-3951',
  'email': 'dapicture@dayrep.com',
  'first_name': 'Drew',
  'last_name': 'Apicture',
  'ssn': '531-22-3951'},
 {'_key': '691-27-5449',
  'email': 'ddewinned02@dayrep.com',
  'first_name': 'Dustin',
  'last_name': 'DeWinned',
  'ssn': '691-27-5449'},
 {'_key': '258-98-7598',
  'email': 'etoudawright@armyspy.com',
  'first_name': 'Eileen',
  'last_name': 'Touda-Wright',
  'ssn': '258-98-7598'},
 {'_key': '363-47-6635',
  'email': 'eileen.toudaleft@einrot.com',
  'first_name': 'Eileen',
  'last_name': 'Touda-Left',
  'ssn': '363-47-6635'},
 {'_key': '997-13-8621',
  'email': 'elieen.onyewe@gustr.com',
  'first_name': 'Elieen',
  'last_name': 'Onyewe',
  'ssn': '997-13-8621'},
 {'_key': '469-19-4101',
  'email': 'edetyers@gustr.com',
  'first_name': 'Erin',
  'last_name': 'Detyers',
  'ssn': '469-19-4101'},
 {'_key': '959-27-3908',
  'email': 'eyortires@gustr.com',
  'first_name': 'Erin',
  'last_name': 'Yortires',
  'ssn': '959-27-3908'},
 {'_key': '404-14-7985',
  'email': 'equittin33@dayrep.com',
  'first_name': 'Eura',
  'last_name': 'Quittin',
  'ssn': '404-14-7985'},
 {'_key': '495-41-3173',
  'email': 'elyre@gustr.com',
  'first_name': 'Eura',
  'last_name': 'Lyre',
  'ssn': '495-41-3173'},
 {'_key': '090-66-7600',
  'email': 'etasomthin@rhyta.com',
  'first_name': 'Euron',
  'last_name': 'Tasomthin',
  'ssn': '090-66-7600'},
 {'_key': '921-76-2688',
  'email': 'efyre@einrot.com',
  'first_name': 'Euron',
  'last_name': 'Fyre',
  'ssn': '921-76-2688'},
 {'_key': '188-64-2144',
  'email': 'ffurter@superrito.com',
  'first_name': 'Frank',
  'last_name': 'Furter',
  'ssn': '188-64-2144'},
 {'_key': '150-80-4134',
  'email': 'frank.klee@gustr.com',
  'first_name': 'Frank',
  'last_name': 'Klee',
  'ssn': '150-80-4134'},
 {'_key': '084-91-2754',
  'email': 'gforcewynds@gustr.com',
  'first_name': 'Gail',
  'last_name': 'Forcewynds',
  'ssn': '084-91-2754'},
 {'_key': '277-33-6106',
  'email': 'gmoore@armyspy.com',
  'first_name': 'Gamble',
  'last_name': 'Moore',
  'ssn': '277-33-6106'},
 {'_key': '035-31-1742',
  'email': 'gling96@rhyta.com',
  'first_name': 'Gamble',
  'last_name': 'Ling',
  'ssn': '035-31-1742'},
 {'_key': '598-88-6830',
  'email': 'ginger.snaps@armyspy.com',
  'first_name': 'Ginger',
  'last_name': 'Snaps',
  'ssn': '598-88-6830'},
 {'_key': '197-38-8981',
  'email': 'ginger.beer@dayrep.com',
  'first_name': 'Ginger',
  'last_name': 'Beer',
  'ssn': '197-38-8981'},
 {'_key': '638-22-3313',
  'email': 'gtoffwind@gustr.com',
  'first_name': 'Gus',
  'last_name': 'Toffwind',
  'ssn': '638-22-3313'},
 {'_key': '706-07-9366',
  'email': 'herchief@einrot.com',
  'first_name': 'Hank',
  'last_name': 'Erchief',
  'ssn': '706-07-9366'},
 {'_key': '731-69-3069',
  'email': 'harry.pits@dayrep.com',
  'first_name': 'Harry',
  'last_name': 'Pits',
  'ssn': '731-69-3069'},
 {'_key': '029-51-0463',
  'email': 'harry.face@gustr.com',
  'first_name': 'Harry',
  'last_name': 'Face',
  'ssn': '029-51-0463'},
 {'_key': '745-80-2669',
  'email': 'heyes@einrot.com',
  'first_name': 'Hazel',
  'last_name': 'Eyes',
  'ssn': '745-80-2669'},
 {'_key': '625-23-8336',
  'email': 'hbarr12@gustr.com',
  'first_name': 'Heath',
  'last_name': 'Barr',
  'ssn': '625-23-8336'},
 {'_key': '106-08-2828',
  'email': 'heywood.yamind@dayrep.com',
  'first_name': 'Heywood',
  'last_name': 'Yamind',
  'ssn': '106-08-2828'},
 {'_key': '990-20-4425',
  'email': 'hstrong@einrot.com',
  'first_name': 'Holden',
  'last_name': 'Strong',
  'ssn': '990-20-4425'},
 {'_key': '397-43-9943',
  'email': 'hyorenose@gustr.com',
  'first_name': 'Holden',
  'last_name': 'Yorenose',
  'ssn': '397-43-9943'},
 {'_key': '093-29-8015',
  'email': 'hjapple@rhyta.com',
  'first_name': 'Hugh',
  'last_name': 'Japple',
  'ssn': '093-29-8015'},
 {'_key': '355-37-7091',
  'email': 'ian.ewe@superrito.com',
  'first_name': 'Ian',
  'last_name': 'Ewe',
  'ssn': '355-37-7091'},
 {'_key': '566-80-6168',
  'email': 'ida.knowe@dayrep.com',
  'first_name': 'Ida',
  'last_name': 'Knowe',
  'ssn': '566-80-6168'},
 {'_key': '137-92-4533',
  'email': 'isabelle.gunnering@armyspy.com',
  'first_name': 'Isabelle',
  'last_name': 'Gunnering',
  'ssn': '137-92-4533'},
 {'_key': '621-81-7042',
  'email': 'iringing35@armyspy.com',
  'first_name': 'Isabelle',
  'last_name': 'Ringing',
  'ssn': '621-81-7042'},
 {'_key': '875-41-8653',
  'email': 'istuckopen@einrot.com',
  'first_name': 'Isadore',
  'last_name': 'Stuckopen',
  'ssn': '875-41-8653'},
 {'_key': '481-46-2587',
  'email': 'ijammed@superrito.com',
  'first_name': 'Isadore',
  'last_name': 'Jammed',
  'ssn': '481-46-2587'},
 {'_key': '519-06-1867',
  'email': 'iornotte@einrot.com',
  'first_name': 'Isreal',
  'last_name': 'Ornotte',
  'ssn': '519-06-1867'},
 {'_key': '401-35-1556',
  'email': 'isreal.difficult@rhyta.com',
  'first_name': 'Isreal',
  'last_name': 'Difficult',
  'ssn': '401-35-1556'},
 {'_key': '084-54-5658',
  'email': 'isandwich@dayrep.com',
  'first_name': 'Ivana',
  'last_name': 'Sandwich',
  'ssn': '084-54-5658'},
 {'_key': '733-30-8645',
  'email': 'jack.itupp@gustr.com',
  'first_name': 'Jack',
  'last_name': 'Itupp',
  'ssn': '733-30-8645'},
 {'_key': '962-74-1277',
  'email': 'jolantern53@superrito.com',
  'first_name': 'Jack',
  'last_name': "O'Lantern",
  'ssn': '962-74-1277'},
 {'_key': '580-04-4817',
  'email': 'jpoole@dayrep.com',
  'first_name': 'Jean',
  'last_name': 'Poole',
  'ssn': '580-04-4817'},
 {'_key': '151-82-5640',
  'email': 'jnetics@gustr.com',
  'first_name': 'Jin',
  'last_name': 'Netics',
  'ssn': '151-82-5640'},
 {'_key': '780-85-4263',
  'email': 'joanne.bill@armyspy.com',
  'first_name': 'Joanne',
  'last_name': 'Bill',
  'ssn': '780-85-4263'},
 {'_key': '693-20-9106',
  'email': 'jking46@rhyta.com',
  'first_name': 'Joe',
  'last_name': 'King',
  'ssn': '693-20-9106'},
 {'_key': '813-76-8243',
  'email': 'jczonou15@armyspy.com',
  'first_name': 'Joe',
  'last_name': 'Czonou',
  'ssn': '813-76-8243'},
 {'_key': '047-33-0921',
  'email': 'jtoudaworld@dayrep.com',
  'first_name': 'Joy',
  'last_name': 'Touda-World',
  'ssn': '047-33-0921'},
 {'_key': '821-88-4450',
  'email': 'jfulle@gustr.com',
  'first_name': 'Joy',
  'last_name': 'Fulle',
  'ssn': '821-88-4450'},
 {'_key': '951-26-6435',
  'email': 'jbugg82@superrito.com',
  'first_name': 'June',
  'last_name': 'Bugg',
  'ssn': '951-26-6435'},
 {'_key': '991-56-0931',
  'email': 'jnipper@gustr.com',
  'first_name': 'June',
  'last_name': 'Nipper',
  'ssn': '991-56-0931'},
 {'_key': '116-76-3974',
  'email': 'jcase65@gustr.com',
  'first_name': 'Justin',
  'last_name': 'Case',
  'ssn': '116-76-3974'},
 {'_key': '027-59-3565',
  'email': 'jthyme01@einrot.com',
  'first_name': 'Justin',
  'last_name': 'Thyme',
  'ssn': '027-59-3565'},
 {'_key': '114-23-3746',
  'email': 'karen.less@einrot.com',
  'first_name': 'Karen',
  'last_name': 'Less',
  'ssn': '114-23-3746'},
 {'_key': '730-89-9449',
  'email': 'kpasdcourse@gustr.com',
  'first_name': 'Kenny',
  'last_name': "Pas-D'course",
  'ssn': '730-89-9449'},
 {'_key': '544-91-7578',
  'email': 'kdoit37@gustr.com',
  'first_name': 'Kenny',
  'last_name': 'Doit',
  'ssn': '544-91-7578'},
 {'_key': '655-52-9508',
  'email': 'kbelevit56@einrot.com',
  'first_name': 'Kent',
  'last_name': 'Belevit',
  'ssn': '655-52-9508'},
 {'_key': '934-66-6867',
  'email': 'kkat@dayrep.com',
  'first_name': 'Kitty',
  'last_name': 'Kat',
  'ssn': '934-66-6867'},
 {'_key': '846-23-7442',
  'email': 'kurt.tain@gustr.com',
  'first_name': 'Kurt',
  'last_name': 'Tain',
  'ssn': '846-23-7442'},
 {'_key': '956-42-2622',
  'email': 'lhvmeehom@armyspy.com',
  'first_name': 'Lee',
  'last_name': 'Hvmeehom',
  'ssn': '956-42-2622'},
 {'_key': '233-52-1663',
  'email': 'lismoore@dayrep.com',
  'first_name': 'Les',
  'last_name': 'Ismoore',
  'ssn': '233-52-1663'},
 {'_key': '100-00-6163',
  'email': 'les.tocleanup@dayrep.com',
  'first_name': 'Les',
  'last_name': 'Tocleanup',
  'ssn': '100-00-6163'},
 {'_key': '586-04-4981',
  'email': 'lmeehom@dayrep.com',
  'first_name': 'Leiv',
  'last_name': 'Meehom',
  'ssn': '586-04-4981'},
 {'_key': '579-29-6079',
  'email': 'lamess@superrito.com',
  'first_name': 'Leiv',
  'last_name': 'Amess',
  'ssn': '579-29-6079'},
 {'_key': '201-56-9564',
  'email': 'lilly.padz@dayrep.com',
  'first_name': 'Lilly',
  'last_name': 'Padz',
  'ssn': '201-56-9564'},
 {'_key': '161-76-0353',
  'email': 'lisa.karfurless@rhyta.com',
  'first_name': 'Lisa',
  'last_name': 'Karfurless',
  'ssn': '161-76-0353'},
 {'_key': '086-45-9695',
  'email': 'ldabridgeda@rhyta.com',
  'first_name': 'Lola',
  'last_name': 'Dabridgeda',
  'ssn': '086-45-9695'},
 {'_key': '299-90-9258',
  'email': 'lmedowne@superrito.com',
  'first_name': 'Loren',
  'last_name': 'Medowne',
  'ssn': '299-90-9258'},
 {'_key': '722-44-7506',
  'email': 'ldabucket@dayrep.com',
  'first_name': 'Loren',
  'last_name': 'Dabucket',
  'ssn': '722-44-7506'},
 {'_key': '551-43-3729',
  'email': 'lenne@gustr.com',
  'first_name': 'Luther',
  'last_name': 'Enne',
  'ssn': '551-43-3729'},
 {'_key': '890-71-9425',
  'email': 'mitdowne44@einrot.com',
  'first_name': 'Mark',
  'last_name': 'Itdowne',
  'ssn': '890-71-9425'},
 {'_key': '662-53-3065',
  'email': 'msmann@armyspy.com',
  'first_name': 'Mark',
  'last_name': 'Smann',
  'ssn': '662-53-3065'},
 {'_key': '527-51-8481',
  'email': 'meyezing19@gustr.com',
  'first_name': 'Martin',
  'last_name': 'Eyezing',
  'ssn': '527-51-8481'},
 {'_key': '166-28-7847',
  'email': 'mary.melator@gustr.com',
  'first_name': 'Mary',
  'last_name': 'Melator',
  'ssn': '166-28-7847'},
 {'_key': '635-04-6283',
  'email': 'mmi@gustr.com',
  'first_name': 'Mary',
  'last_name': 'Mi',
  'ssn': '635-04-6283'},
 {'_key': '721-50-3930',
  'email': 'mfur61@superrito.com',
  'first_name': 'Mattie',
  'last_name': 'Fur',
  'ssn': '721-50-3930'},
 {'_key': '893-26-0616',
  'email': 'marronne07@dayrep.com',
  'first_name': 'Mac',
  'last_name': 'Arronne',
  'ssn': '893-26-0616'},
 {'_key': '995-78-2342',
  'email': 'mdonalds@rhyta.com',
  'first_name': 'Mac',
  'last_name': 'Donalds',
  'ssn': '995-78-2342'},
 {'_key': '104-82-8319',
  'email': 'mintosh@dayrep.com',
  'first_name': 'Mac',
  'last_name': 'Intosh',
  'ssn': '104-82-8319'},
 {'_key': '867-39-4151',
  'email': 'mday40@armyspy.com',
  'first_name': 'May',
  'last_name': 'Day',
  'ssn': '867-39-4151'},
 {'_key': '182-78-1811',
  'email': 'mflies57@rhyta.com',
  'first_name': 'May',
  'last_name': 'Flies',
  'ssn': '182-78-1811'},
 {'_key': '809-65-1116',
  'email': 'mimumm94@dayrep.com',
  'first_name': 'Max',
  'last_name': 'Imumm',
  'ssn': '809-65-1116'},
 {'_key': '225-51-9772',
  'email': 'mrophone@armyspy.com',
  'first_name': 'Mike',
  'last_name': 'Rophone',
  'ssn': '225-51-9772'},
 {'_key': '273-86-4648',
  'email': 'mdupp79@gustr.com',
  'first_name': 'Mike',
  'last_name': 'Dupp',
  'ssn': '273-86-4648'},
 {'_key': '407-27-3291',
  'email': 'minnie.aturedoberman@superrito.com',
  'first_name': 'Minnie',
  'last_name': 'Ature-Doberman',
  'ssn': '407-27-3291'},
 {'_key': '041-48-3728',
  'email': 'mmeadows@superrito.com',
  'first_name': 'Misty',
  'last_name': 'Meadows',
  'ssn': '041-48-3728'},
 {'_key': '873-58-7345',
  'email': 'mshores@dayrep.com',
  'first_name': 'Misty',
  'last_name': 'Shores',
  'ssn': '873-58-7345'},
 {'_key': '291-56-0374',
  'email': 'mless@gustr.com',
  'first_name': 'Morris',

In [55]:
with open('seeddata/employees.json','w') as f:
    json.dump(people,f,indent=4)

In [155]:
from datetime import datetime, timedelta
date = datetime(2018,1,5)
for i in range(24*20):
    date_text = f"{date.year:04}-{date.month:02}-{date.day:02}"
    date_number = f"{date.year:04}{date.month:02}{date.day:02}"
    print(f"insert into pay_periods (payperiod_id, payperiod_date) values ('{date_number}','{date_text}');")
    date = date + timedelta(days=7)

insert into pay_periods (payperiod_id, payperiod_date) values ('20180105','2018-01-05');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180112','2018-01-12');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180119','2018-01-19');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180126','2018-01-26');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180202','2018-02-02');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180209','2018-02-09');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180216','2018-02-16');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180223','2018-02-23');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180302','2018-03-02');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180309','2018-03-09');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180316','2018-03-16');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180323','2018-03-23');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180330','2018-03-30');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180406','2018-04-06');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180413','2018-04-13');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180420','2018-04-20');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180427','2018-04-27');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180504','2018-05-04');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180511','2018-05-11');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180518','2018-05-18');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180525','2018-05-25');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180601','2018-06-01');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180608','2018-06-08');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180615','2018-06-15');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180622','2018-06-22');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180629','2018-06-29');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180706','2018-07-06');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180713','2018-07-13');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180720','2018-07-20');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180727','2018-07-27');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180803','2018-08-03');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180810','2018-08-10');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180817','2018-08-17');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180824','2018-08-24');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180831','2018-08-31');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180907','2018-09-07');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180914','2018-09-14');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180921','2018-09-21');
insert into pay_periods (payperiod_id, payperiod_date) values ('20180928','2018-09-28');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181005','2018-10-05');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181012','2018-10-12');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181019','2018-10-19');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181026','2018-10-26');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181102','2018-11-02');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181109','2018-11-09');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181116','2018-11-16');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181123','2018-11-23');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181130','2018-11-30');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181207','2018-12-07');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181214','2018-12-14');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181221','2018-12-21');
insert into pay_periods (payperiod_id, payperiod_date) values ('20181228','2018-12-28');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190104','2019-01-04');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190111','2019-01-11');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190118','2019-01-18');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190125','2019-01-25');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190201','2019-02-01');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190208','2019-02-08');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190215','2019-02-15');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190222','2019-02-22');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190301','2019-03-01');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190308','2019-03-08');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190315','2019-03-15');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190322','2019-03-22');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190329','2019-03-29');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190405','2019-04-05');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190412','2019-04-12');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190419','2019-04-19');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190426','2019-04-26');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190503','2019-05-03');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190510','2019-05-10');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190517','2019-05-17');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190524','2019-05-24');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190531','2019-05-31');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190607','2019-06-07');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190614','2019-06-14');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190621','2019-06-21');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190628','2019-06-28');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190705','2019-07-05');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190712','2019-07-12');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190719','2019-07-19');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190726','2019-07-26');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190802','2019-08-02');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190809','2019-08-09');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190816','2019-08-16');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190823','2019-08-23');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190830','2019-08-30');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190906','2019-09-06');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190913','2019-09-13');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190920','2019-09-20');
insert into pay_periods (payperiod_id, payperiod_date) values ('20190927','2019-09-27');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191004','2019-10-04');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191011','2019-10-11');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191018','2019-10-18');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191025','2019-10-25');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191101','2019-11-01');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191108','2019-11-08');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191115','2019-11-15');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191122','2019-11-22');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191129','2019-11-29');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191206','2019-12-06');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191213','2019-12-13');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191220','2019-12-20');
insert into pay_periods (payperiod_id, payperiod_date) values ('20191227','2019-12-27');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200103','2020-01-03');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200110','2020-01-10');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200117','2020-01-17');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200124','2020-01-24');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200131','2020-01-31');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200207','2020-02-07');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200214','2020-02-14');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200221','2020-02-21');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200228','2020-02-28');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200306','2020-03-06');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200313','2020-03-13');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200320','2020-03-20');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200327','2020-03-27');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200403','2020-04-03');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200410','2020-04-10');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200417','2020-04-17');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200424','2020-04-24');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200501','2020-05-01');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200508','2020-05-08');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200515','2020-05-15');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200522','2020-05-22');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200529','2020-05-29');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200605','2020-06-05');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200612','2020-06-12');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200619','2020-06-19');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200626','2020-06-26');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200703','2020-07-03');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200710','2020-07-10');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200717','2020-07-17');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200724','2020-07-24');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200731','2020-07-31');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200807','2020-08-07');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200814','2020-08-14');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200821','2020-08-21');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200828','2020-08-28');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200904','2020-09-04');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200911','2020-09-11');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200918','2020-09-18');
insert into pay_periods (payperiod_id, payperiod_date) values ('20200925','2020-09-25');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201002','2020-10-02');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201009','2020-10-09');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201016','2020-10-16');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201023','2020-10-23');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201030','2020-10-30');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201106','2020-11-06');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201113','2020-11-13');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201120','2020-11-20');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201127','2020-11-27');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201204','2020-12-04');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201211','2020-12-11');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201218','2020-12-18');
insert into pay_periods (payperiod_id, payperiod_date) values ('20201225','2020-12-25');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210101','2021-01-01');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210108','2021-01-08');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210115','2021-01-15');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210122','2021-01-22');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210129','2021-01-29');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210205','2021-02-05');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210212','2021-02-12');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210219','2021-02-19');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210226','2021-02-26');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210305','2021-03-05');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210312','2021-03-12');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210319','2021-03-19');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210326','2021-03-26');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210402','2021-04-02');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210409','2021-04-09');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210416','2021-04-16');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210423','2021-04-23');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210430','2021-04-30');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210507','2021-05-07');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210514','2021-05-14');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210521','2021-05-21');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210528','2021-05-28');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210604','2021-06-04');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210611','2021-06-11');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210618','2021-06-18');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210625','2021-06-25');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210702','2021-07-02');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210709','2021-07-09');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210716','2021-07-16');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210723','2021-07-23');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210730','2021-07-30');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210806','2021-08-06');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210813','2021-08-13');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210820','2021-08-20');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210827','2021-08-27');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210903','2021-09-03');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210910','2021-09-10');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210917','2021-09-17');
insert into pay_periods (payperiod_id, payperiod_date) values ('20210924','2021-09-24');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211001','2021-10-01');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211008','2021-10-08');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211015','2021-10-15');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211022','2021-10-22');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211029','2021-10-29');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211105','2021-11-05');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211112','2021-11-12');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211119','2021-11-19');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211126','2021-11-26');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211203','2021-12-03');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211210','2021-12-10');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211217','2021-12-17');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211224','2021-12-24');
insert into pay_periods (payperiod_id, payperiod_date) values ('20211231','2021-12-31');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220107','2022-01-07');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220114','2022-01-14');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220121','2022-01-21');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220128','2022-01-28');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220204','2022-02-04');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220211','2022-02-11');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220218','2022-02-18');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220225','2022-02-25');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220304','2022-03-04');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220311','2022-03-11');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220318','2022-03-18');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220325','2022-03-25');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220401','2022-04-01');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220408','2022-04-08');
insert into pay_periods (payperiod_id, payperiod_date) values ('20220415','2022-04-15');

In [156]:
def create_employee_record(eid, ssn, first_name, last_name, hire_date, jobtitle, department, pay_rate, sid=None ):
    sql = "insert into employees\n"
    sql += "\t(employee_id, employee_ssn, employee_firstname, employee_lastname, employee_hire_date, employee_jobtitle, employee_department, employee_pay_rate, employee_supervisor_employee_id )\n"
    if sid==None:
        sql += f"\t values ({eid},'{ssn}','{first_name}', '{last_name}', '{hire_date}','{jobtitle}','{department}',{pay_rate},NULL);"
    else:
        sql += f"\t values ({eid},'{ssn}','{first_name}', '{last_name}', '{hire_date}','{jobtitle}','{department}',{pay_rate},{sid});"
    return sql

def create_employee_record_sp(start_date, eid, ssn, first_name, last_name, hire_date, jobtitle, department, pay_rate, sid=None ):
    sql = "exec p_employee_upsert "
    if sid==None:
        sql += f"'{start_date}',{eid},'{ssn}','{first_name}', '{last_name}', '{hire_date}',NULL,'{jobtitle}','{department}',{pay_rate},NULL;"
    else:
        sql += f"'{start_date}',{eid},'{ssn}','{first_name}', '{last_name}', '{hire_date}',NULL,'{jobtitle}','{department}',{pay_rate}, {sid};"
    return sql

In [157]:
### SEED EMPLOYEES
with open('seeddata/employees.json','r') as f:
    emps = json.load(f)
    
random.shuffle(emps)
    
jobtitles = ['Store Manager', 'Department Manager', 'Sales Associate']
jobtitles_base_salary = [80000, 50000, 15]
jobtitles_delta_salary = [500, 500, 0.25]
jobtitles_buckets = [10, 13, 21]

departments = [ 'Clothing', 'Customer Service', 'Electronics', 'Hardware', 'Housewares', 'Sporting Goods', 'Toys' ]
department_cum_weights = [ 1, 1.5, 1.33, 1, 1, 1.33, 1.33]
department_sid = {}

start_date='2018-01-01'

# Seed the boss!!
sql = create_employee_record_sp(start_date,1, '123-45-6789', 'Michael', 'Fudge', '2010-04-01', 'Owner', 'Customer Service', 125000/52)
print(sql)

# Seed the store manager # 1
emp = emps.pop()
salary = jobtitles_base_salary[0] + jobtitles_delta_salary[0]*rand_normal_dist(random,jobtitles_buckets[0])
sql =create_employee_record_sp(start_date,2, emp['ssn'],emp['first_name'], emp['last_name'], '2012-05-01', jobtitles[0], 'Customer Service', salary/52, 1)
print(sql)

# Seed the store manager # 2
emp = emps.pop()
salary = jobtitles_base_salary[0] + jobtitles_delta_salary[0]*rand_normal_dist(random,jobtitles_buckets[0])
sql =create_employee_record_sp(start_date,3, emp['ssn'],emp['first_name'], emp['last_name'], '2012-07-01', jobtitles[0], 'Customer Service', salary/52, 1)
print(sql)

eid = 4
for dept in departments:
    # seed the managers
    emp = emps.pop()
    salary = jobtitles_base_salary[1] + jobtitles_delta_salary[1]*rand_normal_dist(random,jobtitles_buckets[1])
    month = random.randint(1,12)
    sql =create_employee_record_sp(start_date,eid, emp['ssn'],emp['first_name'], emp['last_name'], f'2013-{month:02}-01', 'Department Manager', dept, salary/52, random.randint(2,3))
    department_sid[dept]= eid;
    print(sql)
    eid += 1
    
    
depts = random.choices(departments, weights = department_cum_weights , k = 50)
for d in depts:
    #seed the sales associates
    emp = emps.pop()
    hourly_wage = jobtitles_base_salary[2] + jobtitles_delta_salary[2]*rand_normal_dist(random,jobtitles_buckets[2])
    month = rand_normal_dist(random,12) + 1
    year = rand_normal_dist(random,5)+ 2013
    sql =create_employee_record_sp(start_date,eid, emp['ssn'],emp['first_name'], emp['last_name'], f'{year:04}-{month:02}-01', 'Sales Associate', d, hourly_wage, department_sid[d])
    print(sql)
    eid+=1
    

# Seed one manager per department

# seed employees based on cum weighers

exec p_employee_upsert '2018-01-01',1,'123-45-6789','Michael', 'Fudge', '2010-04-01',NULL,'Owner','Customer Service',2403.846153846154,NULL;
exec p_employee_upsert '2018-01-01',2,'958-76-7513','Amber', 'Wavesofgrain', '2012-05-01',NULL,'Store Manager','Customer Service',1567.3076923076924, 1;
exec p_employee_upsert '2018-01-01',3,'047-33-0921','Joy', 'Touda-World', '2012-07-01',NULL,'Store Manager','Customer Service',1605.7692307692307, 1;
exec p_employee_upsert '2018-01-01',4,'161-76-0353','Lisa', 'Karfurless', '2013-06-01',NULL,'Department Manager','Clothing',1019.2307692307693, 3;
exec p_employee_upsert '2018-01-01',5,'151-91-9536','Willie', 'Pas-D'course', '2013-12-01',NULL,'Department Manager','Customer Service',990.3846153846154, 3;
exec p_employee_upsert '2018-01-01',6,'189-32-2043','Bob', 'Enweave', '2013-02-01',NULL,'Department Manager','Electronics',1009.6153846153846, 3;
exec p_employee_upsert '2018-01-01',7,'363-47-6635','Eileen', 'Touda-Left', '2013-10-01',NULL,'Department Manager','Hardware',1009.6153846153846, 2;
exec p_employee_upsert '2018-01-01',8,'528-59-6392','Ty', 'Itdowne', '2013-10-01',NULL,'Department Manager','Housewares',1009.6153846153846, 2;
exec p_employee_upsert '2018-01-01',9,'056-62-8945','Al', 'Frecso', '2013-05-01',NULL,'Department Manager','Sporting Goods',1057.6923076923076, 3;
exec p_employee_upsert '2018-01-01',10,'826-09-9393','Val', 'Idation', '2013-05-01',NULL,'Department Manager','Toys',1019.2307692307693, 3;
exec p_employee_upsert '2018-01-01',11,'197-38-8981','Ginger', 'Beer', '2015-05-01',NULL,'Sales Associate','Clothing',17.25, 4;
exec p_employee_upsert '2018-01-01',12,'882-16-5230','Woodrow', 'Aboate', '2016-08-01',NULL,'Sales Associate','Electronics',17.0, 6;
exec p_employee_upsert '2018-01-01',13,'695-25-9623','Sonny', 'Dayz', '2017-09-01',NULL,'Sales Associate','Toys',17.25, 10;
exec p_employee_upsert '2018-01-01',14,'716-44-7134','Dan', 'Delyons', '2015-03-01',NULL,'Sales Associate','Customer Service',18.0, 5;
exec p_employee_upsert '2018-01-01',15,'760-27-6533','Windy', 'Sees', '2015-08-01',NULL,'Sales Associate','Sporting Goods',17.5, 9;
exec p_employee_upsert '2018-01-01',16,'065-13-3208','Ty', 'Dibol', '2015-06-01',NULL,'Sales Associate','Toys',17.5, 10;
exec p_employee_upsert '2018-01-01',17,'203-71-1878','Myra', 'Sisdone', '2016-06-01',NULL,'Sales Associate','Sporting Goods',19.5, 9;
exec p_employee_upsert '2018-01-01',18,'390-21-0626','Sal', 'Debote', '2015-07-01',NULL,'Sales Associate','Housewares',17.75, 8;
exec p_employee_upsert '2018-01-01',19,'069-99-8924','Phil', 'Itall-Theweigh', '2014-07-01',NULL,'Sales Associate','Electronics',15.25, 6;
exec p_employee_upsert '2018-01-01',20,'084-91-2754','Gail', 'Forcewynds', '2017-03-01',NULL,'Sales Associate','Electronics',17.5, 6;
exec p_employee_upsert '2018-01-01',21,'137-92-4533','Isabelle', 'Gunnering', '2015-04-01',NULL,'Sales Associate','Hardware',16.75, 7;
exec p_employee_upsert '2018-01-01',22,'369-37-9012','Aiden', 'Knowone', '2016-04-01',NULL,'Sales Associate','Sporting Goods',17.5, 9;
exec p_employee_upsert '2018-01-01',23,'273-86-4648','Mike', 'Dupp', '2015-05-01',NULL,'Sales Associate','Sporting Goods',16.5, 9;
exec p_employee_upsert '2018-01-01',24,'778-63-2969','Anita', 'Sandwich', '2016-07-01',NULL,'Sales Associate','Electronics',17.0, 6;
exec p_employee_upsert '2018-01-01',25,'638-22-3313','Gus', 'Toffwind', '2013-08-01',NULL,'Sales Associate','Customer Service',17.25, 5;
exec p_employee_upsert '2018-01-01',26,'415-79-2532','Anita', 'Favor', '2016-10-01',NULL,'Sales Associate','Sporting Goods',17.25, 9;
exec p_employee_upsert '2018-01-01',27,'520-62-3750','Artie', 'Choke', '2015-07-01',NULL,'Sales Associate','Customer Service',18.0, 5;
exec p_employee_upsert '2018-01-01',28,'489-42-0677','Carol', 'Ling', '2015-05-01',NULL,'Sales Associate','Hardware',16.25, 7;
exec p_employee_upsert '2018-01-01',29,'685-84-9242','April', 'First', '2015-10-01',NULL,'Sales Associate','Electronics',17.25, 6;
exec p_employee_upsert '2018-01-01',30,'098-24-5706','Sandy', 'Beeches', '2015-06-01',NULL,'Sales Associate','Hardware',15.75, 7;
exec p_employee_upsert '2018-01-01',31,'143-95-3205','Nat', 'Tural', '2013-05-01',NULL,'Sales Associate','Hardware',17.0, 7;
exec p_employee_upsert '2018-01-01',32,'178-66-2185','Theodore', 'Istrong', '2014-08-01',NULL,'Sales Associate','Hardware',16.75, 7;
exec p_employee_upsert '2018-01-01',33,'093-29-8015','Hugh', 'Japple', '2016-09-01',NULL,'Sales Associate','Toys',18.0, 10;
exec p_employee_upsert '2018-01-01',34,'041-48-3728','Misty', 'Meadows', '2014-07-01',NULL,'Sales Associate','Toys',17.5, 10;
exec p_employee_upsert '2018-01-01',35,'321-52-1883','Doris', 'Closed', '2013-05-01',NULL,'Sales Associate','Hardware',17.0, 7;
exec p_employee_upsert '2018-01-01',36,'140-63-5030','Ally', 'Gator', '2013-06-01',NULL,'Sales Associate','Toys',16.75, 10;
exec p_employee_upsert '2018-01-01',37,'678-51-5677','Otto', 'Moni', '2013-06-01',NULL,'Sales Associate','Hardware',18.0, 7;
exec p_employee_upsert '2018-01-01',38,'881-48-2053','Barb', 'Barion', '2015-07-01',NULL,'Sales Associate','Sporting Goods',17.75, 9;
exec p_employee_upsert '2018-01-01',39,'512-08-0512','Tim', 'Idd', '2014-06-01',NULL,'Sales Associate','Sporting Goods',17.0, 9;
exec p_employee_upsert '2018-01-01',40,'401-35-1556','Isreal', 'Difficult', '2015-02-01',NULL,'Sales Associate','Housewares',17.0, 8;
exec p_employee_upsert '2018-01-01',41,'644-44-2632','Brayden', 'Yourhair', '2015-07-01',NULL,'Sales Associate','Electronics',18.0, 6;
exec p_employee_upsert '2018-01-01',42,'469-19-4101','Erin', 'Detyers', '2015-09-01',NULL,'Sales Associate','Housewares',17.75, 8;
exec p_employee_upsert '2018-01-01',43,'495-41-3173','Eura', 'Lyre', '2014-02-01',NULL,'Sales Associate','Clothing',18.75, 4;
exec p_employee_upsert '2018-01-01',44,'989-69-3061','Candi', 'Kane', '2017-05-01',NULL,'Sales Associate','Electronics',17.5, 6;
exec p_employee_upsert '2018-01-01',45,'520-97-0381','Sal', 'Ladd-Furdiner', '2016-04-01',NULL,'Sales Associate','Customer Service',17.25, 5;
exec p_employee_upsert '2018-01-01',46,'991-56-0931','June', 'Nipper', '2017-05-01',NULL,'Sales Associate','Customer Service',16.5, 5;
exec p_employee_upsert '2018-01-01',47,'817-49-5922','Sue', 'Mii', '2014-05-01',NULL,'Sales Associate','Hardware',18.25, 7;
exec p_employee_upsert '2018-01-01',48,'842-53-5067','Willow', 'Wisp', '2014-05-01',NULL,'Sales Associate','Housewares',17.5, 8;
exec p_employee_upsert '2018-01-01',49,'434-67-0804','Ty', 'Anott', '2016-04-01',NULL,'Sales Associate','Toys',17.75, 10;
exec p_employee_upsert '2018-01-01',50,'112-63-5069','Pete', 'Moss', '2015-07-01',NULL,'Sales Associate','Toys',16.5, 10;
exec p_employee_upsert '2018-01-01',51,'407-27-3291','Minnie', 'Ature-Doberman', '2014-05-01',NULL,'Sales Associate','Sporting Goods',17.25, 9;
exec p_employee_upsert '2018-01-01',52,'151-82-5640','Jin', 'Netics', '2015-06-01',NULL,'Sales Associate','Customer Service',17.25, 5;
exec p_employee_upsert '2018-01-01',53,'581-41-4823','Bette', 'Alott', '2013-06-01',NULL,'Sales Associate','Electronics',16.25, 6;
exec p_employee_upsert '2018-01-01',54,'777-43-2728','Alma', 'Frienzergon', '2015-07-01',NULL,'Sales Associate','Customer Service',17.75, 5;
exec p_employee_upsert '2018-01-01',55,'781-00-9353','Adam', 'Antium', '2016-06-01',NULL,'Sales Associate','Electronics',18.5, 6;
exec p_employee_upsert '2018-01-01',56,'997-13-8621','Elieen', 'Onyewe', '2017-04-01',NULL,'Sales Associate','Customer Service',16.25, 5;
exec p_employee_upsert '2018-01-01',57,'277-33-6106','Gamble', 'Moore', '2016-04-01',NULL,'Sales Associate','Customer Service',16.75, 5;
exec p_employee_upsert '2018-01-01',58,'573-00-7626','Al', 'Kohol', '2015-08-01',NULL,'Sales Associate','Toys',17.75, 10;
exec p_employee_upsert '2018-01-01',59,'875-41-8653','Isadore', 'Stuckopen', '2015-04-01',NULL,'Sales Associate','Clothing',17.0, 4;
exec p_employee_upsert '2018-01-01',60,'531-22-3951','Drew', 'Apicture', '2015-02-01',NULL,'Sales Associate','Customer Service',17.5, 5;

In [153]:
d2 ={}
for d in depts:
    d2[d]  = d2.get(d,0) +1
    
d2

{'Clothing': 5,
 'Customer Service': 12,
 'Sporting Goods': 5,
 'Hardware': 7,
 'Housewares': 9,
 'Electronics': 5,
 'Toys': 7}

In [127]:
help(random.choices)

Help on method choices in module random:

choices(population, weights=None, *, cum_weights=None, k=1) method of random.Random instance
    Return a k sized list of population elements chosen with replacement.

    If the relative weights or cumulative weights are not specified,
    the selections are made with equal probability.